#プレフィックスキーの変更
unbind C-b
set -g prefix C-w
bind C-w send-prefix

# OSC 52を用いたシステムクリップボードへのアクセスを有効化
set -g set-clipboard on

# ペインでの変更を通知
set -g focus-events on

#tmuxを256色表示できるようにする
set -ga terminal-features "xterm-256color:RGB"
set -ga terminal-overrides  "xterm-256color:RGB"

#ステータスバーをトップに配置する
set-option -g status-position top

#左右のステータスバーの長さを決定する
set-option -g status-left-length 90
set-option -g status-right-length 90

# #P => ペイン番号
#最左に表示
set-option -g status-left "#H:[#S]"

#最左に表示
set-option -g status-right "[%Y-%m-%d(%a) %H:%M]"

#表示を簡素化
set-option -g window-status-format "#I:#W"
set-option -g window-status-current-format "#I:#W*"

#ステータスバーを一秒ごとに描画し直す
set-option -g status-interval 1

#センタライズ(主にウィンドウ番号など)
set-option -g status-justify centre

#ステータスバーの色を設定する
set-option -g status-bg "colour238"

#ステータスバーの色を設定する
set-option -g status-fg "colour255"

#ズームのバインド変更
unbind z
bind + resize-pane -Z

#新しいセッション，ウィンドウ
bind o new-session
bind i new-window

#vimのキーバインドでペインを移動する
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

#vimのキーバインドでペインをリサイズする
bind -n C-h resize-pane -L 5
bind -n C-j resize-pane -D 5
bind -n C-k resize-pane -U 5
bind -n C-l resize-pane -R 5

# \でペインを縦分割する
bind | split-window -h

# _でペインを縦分割する
bind _ split-window -v

# Spaceでのレイアウト変更を無効化
unbind Space

#コピーモードでvim キーバインドを使う
setw -g mode-keys vi

#ESCの反応が遅い問題の解消
set -g escape-time 0

#スクロールできる範囲の拡大
set -g history-limit 100000

#v で選択
bind -T copy-mode-vi v send -X begin-selection

#V で選択
bind -T copy-mode-vi V send -X select-line

#C-v で選択
bind -T copy-mode-vi C-v send -X rectangle-toggle

#y でヤンク
bind -T copy-mode-vi y send -X copy-selection

#Y で行ヤンク
bind -T copy-mode-vi Y send -X copy-line
